name = "react-portable"
main = ".portable/server/worker.mjs"
compatibility_date = "2023-05-10"

[build]
command = "npx portable build --continuous"
watch_dir = "src"

[site]
bucket = ".portable/client"