name = "gateway"
main = "src/worker.ts"
compatibility_date = "2023-05-30"

kv_namespaces = [
    { binding = "STORE", id = "yyyyyyyyyyyyyyyy", preview_id = "xxxxxxxxxxxxxxxxx" }
]

[vars]
ORIGIN = "https://0.0.0.0"
COMPONENT_DELIVERING_SYSTEMS = '{"cds":{"endpoint":"http://0.0.0.0:3001","assetPath":""}}'
ALLOW_ORIGINS = "http://0.0.0.0:3000, http://0.0.0.0:3001"