name: Run Tests

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup dependencies
        uses: ./.github/actions/setup-dependencies

      - name: 🧪Run Tests
        run: yarn test
